config/routes.rb
Ticketee::Application.routes.draw do
  resources :products

  
  root :to => "projects#index"
  
  resources :projects do
    resources :tickets
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible  :name, :description
  
  validates :name, :presence => true
  
  has_many :tickets
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :project_id
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  attr_accessible :description, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :find_project, :only => [:show, :edit, :update, :destroy]
  
  def index
	@projects = Project.all
  end
  
  def new
    @project = Project.new(params[:project])
	@project.save
  end
  
  def create
    @project = Project.new(params[:project]) # <co id="ch03_501_1"/>
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
	  #<co id="ch03_926_1"/>
	  render :action => "new"
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
	if @project.update_attributes(params[:project])
	  flash[:notice] = "Project has been updated."
	  redirect_to @project
	else
	  flash[:alert] = "Project has not been updated."
	  render :action => "edit"
	end
  end
  
  def destroy
	@project.destroy
	flash[:notice] = "Project has been deleted."
	redirect_to projects_path
  end
  
  private
	def find_project
	  @project = Project.find(params[:id])
	  rescue ActiveRecord::RecordNotFound
	  flash[:alert] = "The project you were looking for could not be found."
	  redirect_to projects_path
	end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_project
  
  def new
    @ticket = @project.tickets.build
  end
  
  def create
    @ticket = @project.tickets.build(params[:ticket])
	if @ticket.save
	  flash[:notice] = "Ticket has been created."
	  redirect_to [@project, @ticket]
	else
	  flash[:alert] = "Ticket has not been created."
	  render :action => "new"
	end
  end
  
  private
    def find_project
	  @project = Project.find(params[:project_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts) #<co id="ch03_790_1"/>
    unless parts.empty?
	  content_for :title do
	    (parts << "Ticketee").join(" - ")
	  end
	end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
	  <%= yield(:title) %>
	<% else %>
	  Ticketee
	<% end %>
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% flash.each do |key, value| %>
  <div class='flash' id='<%=key %>'>
    <%= value %>
  </div>
 <% end %>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %> <co id="ch03_501_1"/>
<%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
	<%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :description %><br />
	<%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb

<%= link_to "New Project", new_project_path %>
<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form" %>
  

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project",
	project_path(@project),
	:method => :delete,
	:confirm => "Are you sure you want to delete this project?" %>
	
<%= link_to "New Ticket", new_project_ticket_path(@project) %>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br>
	  </programlisting>
	  </informalexample>
	<%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
	<%= f.text_area :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>